# delpoy.yml
name: Deploy FastAPI-Service

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        # run: pytest -v --disable-warnings
        run: pytest -v tests/test_cat.py tests/test_weather.py --disable-warnings

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test  # ⚠️ Запускается ТОЛЬКО если job test прошёл успешно

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/FastAPI-Service

            # Остановка сервиса и очистка логов
            systemctl stop fastapi.service || true
            [ -f fastapi_service.log ] && rm fastapi_service.log
            
            # Синхронизация последних изменений
            git fetch origin main --depth=1
            git reset --hard FETCH_HEAD
            
            # Обновление зависимостей
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt --no-cache-dir
            
            # Запуск сервиса
            echo "0" > visits.txt
            systemctl start fastapi.service
            echo "✅ Deployment completed"

      - name: Set CI status env
        run: echo "STATUS=✅ Успешно" >> $GITHUB_ENV

      - name: Prepare CI payload
        id: prepare_payload
        run: |
          echo "Создаём JSON для CI-репорта"
          echo '{
            "secret": "'"${{ secrets.CI_SECRET }}"'",
            "project": "'"${{ github.repository }}"'",
            "status": "'"$STATUS"'",
            "commit": "'"$(git rev-parse --short HEAD)"'",
            "author": "'"${{ github.actor }}"'",
            "branch": "'"${{ github.ref_name }}"'",
            "workflow": "'"${{ github.workflow }}"'",
            "event_name": "'"${{ github.event_name }}"'",
            "message": "'"${{ github.event.head_commit.message }}"'",
            "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "repo_url": "https://github.com/${{ github.repository }}"
          }' > ci_payload.json
          echo "payload_file=ci_payload.json" >> $GITHUB_OUTPUT

      - name: Send CI Report to Telegram Bot
        env:
          CI_ENDPOINT: ${{ secrets.CI_ENDPOINT }}
        run: |
          echo "📡 Отправляем CI-отчёт..."
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$CI_ENDPOINT" \
            -H "Content-Type: application/json" \
            -d @"${{ steps.prepare_payload.outputs.payload_file }}")

          if [[ "$HTTP_CODE" -ne 200 ]]; then
            echo "::warning::CI report failed with HTTP $HTTP_CODE"
            exit 1
          else
            echo "✅ CI-отчёт успешно отправлен. Код ответа: $HTTP_CODE"
          fi